services:
  web:
    build:
      context: . # Cambiar el contexto a la raíz del proyecto
      dockerfile: nginx/Dockerfile 
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: inmobiliaria_db
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
